### ISSUE TITLE
How to develop the model on my local machine? 

### ISSUE THREAD

**Issue by void-echo** [ddzipp/AutoAudit#3]
Is there any step-by-step tutorials?

**Comment by lilBuffaloEric** [comment]
Step-by-step tutorials are coming soon in the next release.

**Comment by chenzebiaohub** [comment]
Coming on！we need~ Thanks

**Comment by ddzipp** [comment]
> Coming on！we need~ Thanks

hi, we have finished a setup tutorials https://github.com/ddzipp/AutoAudit/blob/main/sandbox/README.md.
